### PR TITLE
Add f2s readme

### PR DESCRIPTION
**Pull request by cvieri**

### CODE REVIEW

**Comment by pigmej** [comment]
Do we need #367 before that ?

**Comment by cvieri** [comment]
Not sure, actually it works w/o this PR.

**Comment by pigmej** [comment]
@dshulyak up to you.

**Comment by dshulyak** [comment]
i think merging makes sense only after f2s

**Comment by dshulyak** [comment]
messed up with previous pr, new one in https://github.com/Mirantis/solar/pull/395

**Pull request merged**
